mednet_sum_site/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView, upload_raw_json_data, download_raw_json_data


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'), # home.html設定
    path('accounts/', include('django.contrib.auth.urls')),
    path('questions/', include('question.urls')),
    path('task/', include('task.urls')),
    path('label/', include('labeling.urls')),
    path('labeltask/', include('labeltask.urls')),
    path('data/upload_file/', upload_raw_json_data, name='upload_raw_json_data'),#沒有寫在網頁裡 要自己打
    path('data/download_file/', download_raw_json_data, name='download_raw_json_data'),#沒有寫在網頁裡 要自己打
]

task/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.task_situations, name='task_situations'),
    path('distribute_task/', views.distribute_task, name='distribute_task'),
    # path('assign_task', )
]

question/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.contrib.auth.models import User

# Create your models here.


class Question(models.Model):
    qQuestion_ID = models.IntegerField(primary_key=True, unique=True)
    qQuestion_Title = models.CharField(max_length=100)
    qOriginal_Question = models.TextField(max_length=1000)
    QUES_TYPE_CHOICES = (
        (0, '未選擇 NOT selected'),
        (1, '病症 symptoms'),
        (2, '藥物 drugs'),
        (3, '科室 department'),
        (4, '治療 treatment'),
        (5, '檢查 examination'),
        (6, '資訊 informantion'),
        (7, '再討論...')
    )
    QUES_FILTER = (
        (0, "Haven't filter"),
        (1, 'Single'),
        (2, 'Single & Often'),
        (3, 'Multi'),
        (4, 'Discuss'),
        (5, 'Trash')
    )
    sQuery = models.TextField(
        max_length=500, null=True, blank=True, default=None)
    sQuestion_Type = models.PositiveSmallIntegerField(
        null=True, choices=QUES_TYPE_CHOICES, default=None)
    sQuestion_Filter = models.PositiveSmallIntegerField(
        null=True, choices=QUES_FILTER, default=None)

    def __str__(self):
        return 'id: {}'.format(self.qQuestion_ID)



class Summarization(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    Time_stamp = models.TimeField(default=timezone.now)
    sUser = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return "summarization: id{}".format(self.question.qQuestion_ID)


# class WhoIsGoingToSum(models.Model):
#     question = models.ForeignKey(Question, on_delete=models.CASCADE)
#     WUser = models.ForeignKey(settings.A, on_delete=models.SET_NULL, null=True)

templates/label/admin_review_labels.html
{% extends "base.html" %}
{% block title %}
<title>標記介面</title>
{% endblock %}

{% block content %}
<p>問題ID: {{question.qQuestion_ID}}</p>
<p>問題Title: {{question.qQuestion_Title}}</p>
<div class="form-group">
    <form method="post">
        {% csrf_token %}
        {{review_form.as_p}}
        <div class="container">
            <div class="row">
                <div class="col justify-content-start">
                    <div class="text-left">
                        <input type="button" value="prev" class="btn btn-outline-dark" onclick="location.href='/label/admin_review_labels/{{question.qQuestion_ID}}/prev/True/'">
                    </div>
                </div>
                <div class="col-8">
                    <div class="text-center">
                        <button type="submit" class="btn btn-outline-primary" name="ques_filter" value="single">確認</button>
                        <button type="submit" class="btn btn-outline-info" name="ques_filter" value="multi">多重</button>
                    </div>
                </div>
                <div class="col">
                    <div class="text-right">
                        <input type="button" value="next" class="btn btn-outline-dark" onclick="location.href='/label/admin_review_labels/{{question.qQuestion_ID}}/next/True/'">
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<table class="table">
    <thead>
        <tr>
            <th scope="col">項目</th>
            {% for label in labels %}
            <th scope="col">{{label.LUser}}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">充分性</th>
            {% for label in labels %}
            <td>{{label.LAdequacy}}</td>
            {% endfor %}
        </tr>
        <tr>
            <th scope="row">可演繹性</th>
            {% for label in labels %}
            <td>{{label.LDeducibility}}</td>
            {% endfor %}
        </tr>
        <tr>
            <th scope="row">抽象性</th>
            {% for label in labels %}
            <td>{{label.LAbstractive}}</td>
            {% endfor %}
        </tr>
        <tr>
            <th scope="row">備註</th>
            {% for label in labels %}
            <td>{{label.LNote}}</td>
            {% endfor %}
        </tr>
    </tbody>
    </table>
    
{% endblock content %}

{% block nav_label %} active {% endblock %}

templates/label/label_date_rough_see.html
{% extends "base.html" %}
{% block title %}
<title>標記問題</title>
{% endblock%}
{% block content %}
<div class="row">
    <div class="col">
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleFormControlSelect2">還未摘要</label>
                <select class="form-control" id="exampleFormControlSelect2" name="label_id">
                    {% for labeltask in undone %}
                    <option value="{{labeltask.tQuestion.qQuestion_ID}}">{{labeltask.tQuestion.qQuestion_ID}}</option>
                    {% endfor%}
                </select>
            </div>
            <div class="text-center">
                <input type="submit" value="Go!!" class="btn btn-outline-dark"> 
            </div>
        </form>
    </div>
    <div class="col">
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleFormControlSelect2">已完成摘要</label>
                <select class="form-control" id="exampleFormControlSelect2" name="summary_id">
                    {% for labeltask in done %}
                    <option value="{{labeltask.tQuestion.qQuestion_ID}}">{{labeltask.tQuestion.qQuestion_ID}}</option>
                    {% endfor%}
                </select>
            </div>
            <div class="text-center">
                <input type="submit" value="Go!!" class="btn btn-outline-dark"> 
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block nav_label %} active {% endblock %}

templates/label/label_ques_id.html
{% extends "base.html" %}
{% block title %}
<title>標記介面</title>
{% endblock %}

{% block content %}
<div >
    {% if done_or_not %}
        <div class="alert alert-success" role="alert">
            已標記過
      </div>
    {% endif %}
</div>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col" style="width: 10%;">#</th>
            <th scope="col">內容</th>
        </tr>
    </thead>
        <tbody>
        <tr>
            <th scope="row">問題 ID</th>
            <td>{{med_question_list.qQuestion_ID}}</td>
        </tr>
        <tr>
            <th scope="row">問題Title</th>
            <td>{{med_question_list.qQuestion_Title}}</td>
        </tr>
        <tr>
            <th scope="row">原始問句</th>
            <td>{{med_question_list.qOriginal_Question}}</td>
        </tr>
        <tr>
            <th scope="row">摘要問句</th>
            <td>{{med_question_list.sQuery}}</td>
        </tr>
        <tr>
            <th scope="row">問題Type</th>
            <td>{{med_question_list.get_sQuestion_Type_display}}</td>
        </tr>
        </tbody>
    
</table>

<div>
    <form method="POST">
        {% csrf_token %}
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text">&ensp;充分性&ensp;</span>
            </div>
            {{ label_form.LAdequacy }}
            <button class="btn btn-outline-secondary" type="button" onclick="document.getElementById('id_LAdequacy').value=1">True</button>
            <button class="btn btn-outline-secondary" type="button" onclick="document.getElementById('id_LAdequacy').value=0">False</button>
        </div>
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text">可演繹性</span>
            </div>
            {{ label_form.LDeducibility }}
            <button class="btn btn-outline-secondary" type="button" onclick="document.getElementById('id_LDeducibility').value=1">True</button>
            <button class="btn btn-outline-secondary" type="button" onclick="document.getElementById('id_LDeducibility').value=0">False</button>
        </div>
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text">&ensp;抽象性&ensp;</span>
            </div>
            {{ label_form.LAbstractive }}
            <button class="btn btn-outline-secondary" type="button" onclick="document.getElementById('id_LAbstractive').value=1">True</button>
            <button class="btn btn-outline-secondary" type="button" onclick="document.getElementById('id_LAbstractive').value=0">False</button>
        </div>
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text">&emsp;備註&emsp;</span>
            </div>
            {{ label_form.LNote }}
        </div>
        <div class="container">
            <div class="row">
                <div class="col">
                    <input type="button" value="prev" class="btn btn-outline-dark" onclick="location.href='/label/do_label/{{date}}/{{ques_id}}/prev/True'"> 
                    <input type="button" value="next" class="btn btn-outline-dark" onclick="location.href='/label/do_label/{{date}}/{{ques_id}}/next/True'">
                </div>
                <div class="col">
                    <div class="text-right">
                        <button type="submit" class="btn btn-outline-primary">&emsp;確認&emsp;</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
    {% if error %}
    <div class="alert alert-danger" role="alert">
        {{error_msg}}
    </div>
    {% endif %}
</div>
{% endblock content %}

{% block nav_label %} active {% endblock %}

templates/label/your_label_tasks.html
{% extends "base.html" %}

{% block content%}
<div>
    {% if superuser == True %}
        <a href="{% url 'admin_review_labels_next' 20 False %}">審查標記</a>
    {% endif %}

    <ul class="list-group list-group-flush">
    {% for date, percent in data_situation.items%}
    
        <li class="list-group-item">
            <div>
                <div>
                    <a href="{% url 'label_date_rough_see' date %}">任務開始日期：{{date}}</a>
                </div>
                <div class="progress">
                    <div class="progress-bar bg-success" role="progressbar" style="width:{{percent}}%" aria-valuenow="{{percent}}" aria-valuemin="0" aria-valuemax="100">{{percent}}%</div>
                </div>
            </div>
        </li>
    {% endfor %}
    </ul>

</div>
{% endblock %}

{% block nav_label %} active {% endblock %}